### ISSUE TITLE
BUG#04 เข้าด้วยUser: Lab Team Lead ช่องรออนุมัติ ทำdาร comment และกดอนุมัติ 2 ครั้ง จากนั้นกลับมาที่ช่อง งานที่อนุมัติแล้ว History Comment มี comment เบิ้ลเข้ามา

### ISSUE THREAD

**Issue by Marisassss** [Marisassss/-SIT-LAB#4]
หมายเลข LTR  :  03-0-1-00212-0-23-00029

![Image](https://github.com/Marisassss/-SIT-LAB/assets/143678415/94fbe7dd-230c-4409-ad20-404188584273)

**Comment by thanapojPTG** [comment]
อันนี้ปิดเคสได้เลยครับ เป็นที่ระบบเชิง Logic ครับ
