### ISSUE TITLE
BUG#06 ผลิตภัณฑ์ PT Max Diesel B7 ประเภทตัวอย่าง TRUCK Export รายงานเเล้วแต่ข้อมูลไม่ครบ

### ISSUE THREAD

**Issue by Marisassss** [Marisassss/-SIT-LAB#6]
Lab Code : 06-0-3-00212-0-22-03430

![Image](https://github.com/Marisassss/-SIT-LAB/assets/143678415/7bb1628d-d500-424b-8398-717b99158401)

**Comment by thanapojPTG** [comment]
ข้อมูลอาจจะยังไม่สมบูรณ์เดี๋ยวพี่จะ Configuration ไป Production ทดสอบดูเองครับ

**Comment by thanapojPTG** [comment]
สาเหตุดังกล่าวเกิดจาก User ที่ออก Report ไม่ได้ Upload Signature 
ขอปิดเคสครับ กรณีนี้เจอบ่อยครับ
