### ISSUE TITLE
BUG#08 หน้าบันทึกข้อมูลตัวอย่าง เมื่อทำกดเข้าเมนูแล้วโปรแกรมจะค้างอยู่สักพัก

### ISSUE THREAD

**Issue by Sun1212312121** [Marisassss/-SIT-LAB#8]
![Image](https://github.com/Marisassss/-SIT-LAB/assets/140136077/ec387320-9ca5-4d9d-a3b8-dc7e5462e5b2)

**Comment by thanapojPTG** [comment]
อันนี้เป็นเรื่องปกติครับ ตัว Production ก็เป็นขอปิดเคสครับ ตัวนี้ต้องไปแก้เชิง Logic
